name: Test

on:
  push:
    branches: [ release/1.0 ]
  pull_request:
    branches: [ release/1.0 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Build
      run: |
        npm ci
        npm run build

    - name: Test
      uses: cypress-io/github-action@v2
      with:
        browser: chrome
        spec: tests/integration/basic_spec.js
